name: JourneyLands
version: ${project.version}
main: me.majeek.journeylands.Main
api-version: 1.15
authors: [Majeek]
description: Core plugin for JourneyLands
website: journeylands.ddns.net
commands:
  journeylands:
    description: Core command.
    aliases: [jl, xpbottle]